[package]
name = "cargo-bloat"
version = "0.5.0"
authors = ["Reizner Evgeniy <razrfalcon@gmail.com>"]
description = "Find out what takes most of the space in your executable."
repository = "https://github.com/RazrFalcon/cargo-bloat"
readme = "README.md"
license = "MIT"

[dependencies]
cargo = "0.27"
env_logger = "0.5.1"
failure = "0.1.1"
goblin = "0.0.15"
memmap = "0.6"
multimap = "0.4"
object = "0.8"
regex = "1.0.0"
rustc-demangle = "0.1.6"
structopt = "0.2"
term_size = "0.3.1"
