[package]
name = "cargo-bloat"
version = "0.2.0"
authors = ["Reizner Evgeniy <razrfalcon@gmail.com>"]
description = "Find out what takes most of the space in your executable."
repository = "https://github.com/RazrFalcon/cargo-bloat"
readme = "README.md"
license = "MIT"

[dependencies]
cargo = "0.24.0"
docopt = "0.8.1"
env_logger = "0.5.1"
goblin = "0.0.13"
memmap = "0.6"
object = "0.7"
rustc-demangle = "0.1.5"
serde = "1.0.11"
serde_derive = "1.0.11"
term_size = "0.3.1"
